#!/usr/bin/env python3
"""vault_spec_generate_catalog — Auto-generate vault_mcp_catalog.py from tool-spec.json.

Source of truth: scripts/tool-spec.json (structural).
Metadata source:  existing vault_mcp_catalog.py (manual entries).
Output:           Merge — spec provides name/group, catalog provides purpose/params.

Usage:
    python scripts/vault_spec_generate_catalog.py --check  # preview without writing
    python scripts/vault_spec_generate_catalog.py          # write to stdout
    python scripts/vault_spec_generate_catalog.py --write  # write to vault_mcp_catalog.py

The generated catalog merges:
  - Structural data from tool-spec.json: name, group, status, required_args
  - Manual data from existing catalog: purpose, params (with validators), guards, side_effects

If a tool exists in tool-spec.json but not in catalog, it gets a stub.
If a tool exists in catalog but not in spec, it stays (catalog is allowed to be
additionally detailed).
"""

import argparse
import json
import sys
from pathlib import Path

from vault_errors import wrap_main

_HERE = Path(__file__).resolve().parent


def _load_spec() -> dict:
    return json.loads((_HERE / "tool-spec.json").read_text(encoding="utf-8"))


def _load_catalog_source() -> str:
    return (_HERE / "vault_mcp_catalog.py").read_text(encoding="utf-8")


def _extract_dict_from_source(source: str, var_name: str) -> dict:
    """Crude extraction of a module-level dict literal from Python source."""
    start = source.find(f"{var_name}: Dict[str, Dict[str, Any]] = {{")
    if start < 0:
        start = source.find(f"{var_name} = {{")
    if start < 0:
        return {}
    brace_start = source.find("{", start)
    depth = 0
    i = brace_start
    while i < len(source):
        c = source[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                literal = source[brace_start : i + 1]
                try:
                    return json.loads(literal)
                except Exception:
                    return {}
        i += 1
    return {}


def _purpose_for(required_args: list, group: str) -> str:
    return f"{group} tool (auto-stubs from tool-spec.json). Args: {', '.join(required_args)}"


def generate_catalog() -> dict:
    spec = _load_spec()
    source = _load_catalog_source()
    existing = _extract_dict_from_source(source, "TOOLS_CATALOG")

    generated = {}

    for tool_name, spec_entry in spec["tools"].items():
        if tool_name in existing:
            existing_entry = dict(existing[tool_name])
            existing_entry["group"] = spec_entry.get(
                "group", existing_entry.get("group", "Other")
            )
            existing_entry["status"] = spec_entry.get("status", "active")
            existing_entry["required_args"] = spec_entry.get("required_args", [])
            existing_entry["source"] = "merged"
            generated[tool_name] = existing_entry
        else:
            required_args = spec_entry.get("required_args", [])
            generated[tool_name] = {
                "name": tool_name,
                "script": f"{tool_name}.py",
                "group": spec_entry.get("group", "Other"),
                "status": spec_entry.get("status", "active"),
                "purpose": _purpose_for(required_args, spec_entry.get("group", "")),
                "params": {},
                "guards": [],
                "side_effects": [],
                "example": "",
                "related": [],
                "source": "auto-stub",
            }

    for tool_name, entry in existing.items():
        if tool_name not in generated:
            entry_copy = dict(entry)
            entry_copy["status"] = "active"
            entry_copy["source"] = "catalog-only"
            generated[tool_name] = entry_copy

    return generated


def render_python(catalog: dict) -> str:
    lines = [
        "#!/usr/bin/env python3",
        '"""',
        "Vault MCP Catalog — Canonical catalog of vault tools.",
        "",
        "AUTO-GENERATED by vault_spec_generate_catalog.py from tool-spec.json.",
        "Source-of-truth: scripts/tool-spec.json (group, status, required_args).",
        "Manually enriched fields (purpose, params, validators, guards) preserved",
        "from the original catalog.",
        "",
        "Do NOT edit by hand — re-run the generator after editing tool-spec.json.",
        '"""',
        "",
        "from typing import Any, Dict",
        "",
        "",
        "TOOLS_CATALOG: Dict[str, Dict[str, Any]] = " + _pretty_dict(catalog),
        "",
    ]
    return "\n".join(lines)


def _pretty_dict(d: dict) -> str:
    return json.dumps(d, indent=4, ensure_ascii=False, sort_keys=True)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate vault_mcp_catalog.py from tool-spec.json"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare current file vs generated; show diff stats",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Overwrite vault_mcp_catalog.py with generated content",
    )
    args = parser.parse_args()

    catalog = generate_catalog()
    rendered = render_python(catalog)

    if args.check:
        current = (_HERE / "vault_mcp_catalog.py").read_text(encoding="utf-8")
        print(f"Generated size: {len(rendered)} chars, {rendered.count(chr(10))} lines")
        print(f"Current size:   {len(current)} chars, {current.count(chr(10))} lines")
        generated_tools = {
            k for k, v in catalog.items() if v.get("source") == "auto-stub"
        }
        print(f"Auto-stub tools (need enrichment): {len(generated_tools)}")
        if generated_tools:
            for t in sorted(generated_tools)[:10]:
                print(f"  - {t}")
            if len(generated_tools) > 10:
                print(f"  ... and {len(generated_tools) - 10} more")
        return 0

    if args.write:
        out_path = _HERE / "vault_mcp_catalog.py"
        out_path.write_text(rendered, encoding="utf-8")
        print(f"Wrote {len(rendered)} chars to {out_path}")
        return 0

    if args.write:
        out_path = Path("scripts/vault_mcp_catalog.py")
        out_path.write_text(rendered, encoding="utf-8")
        print(f"Wrote {len(rendered)} chars to {out_path}")
        return 0

    print(rendered)
    return 0


if __name__ == "__main__":
    sys.exit(wrap_main(main, "vault_spec_generate_catalog"))
