#!/usr/bin/env python3
"""
Vault MCP Catalog — Catálogo canónico de tools del vault.

Contiene la definición de todas las 69 tools con sus:
- Propósito
- Parámetros
- Validadores
- Guards
- Efectos secundarios
- Ejemplos
- Tools relacionadas

Este catálogo es la fuente de verdad para el orquestador MCP.
"""

from typing import Any, Dict, List, Optional


TOOLS_CATALOG: Dict[str, Dict[str, Any]] = {
    "vault_write": {
        "name": "vault_write",
        "script": "vault_write.py",
        "group": "Core",
        "purpose": "Crea o actualiza notas con frontmatter YAML correcto. Versiona en .history/ antes de sobreescribir.",
        "params": {
            "folder": {
                "type": "string",
                "required": True,
                "description": "Ruta relativa al vault (ej: 01_Projects/mi-api)",
                "validators": ["no_absolute", "no_traversal", "within_vault"],
            },
            "title": {
                "type": "string",
                "required": True,
                "description": "Título de la nota",
                "validators": ["not_empty", "max_length:200"],
            },
            "content": {
                "type": "string",
                "required": True,
                "description": "Contenido Markdown. Usar @file:ruta para leer de archivo",
                "validators": [
                    "min_lines:3",
                    "min_words:10",
                    "no_empty_bullets",
                    "no_path_anchored_links",
                    "no_bracket_anomalies",
                ],
            },
            "tags": {
                "type": "list",
                "required": False,
                "description": "Etiquetas separadas por espacio",
                "validators": [],
            },
            "meta": {
                "type": "json",
                "required": False,
                "description": "JSON con frontmatter adicional",
                "validators": ["valid_json"],
            },
            "meta-file": {
                "type": "string",
                "required": False,
                "description": "Ruta a archivo JSON con frontmatter adicional",
                "validators": ["file_exists", "valid_json_file"],
            },
        },
        "guards": [
            "AP-20 (no bullets vacíos)",
            "AP-21 (no [[/note]])",
            "AP-22 (no [[]] vacíos)",
        ],
        "side_effects": [
            "Versiona en .history/",
            "Actualiza search-index.json",
            "Regenera section index",
        ],
        "example": 'python vault_write.py --folder "01_Projects/mi-api" --title "Overview" --content "# Overview\\n\\nAPI REST" --tags "api backend"',
        "related": ["vault_read", "vault_append", "vault_audit"],
    },
    "vault_read": {
        "name": "vault_read",
        "script": "vault_read.py",
        "group": "Core",
        "purpose": "Lee una nota del vault por ruta relativa o por título.",
        "params": {
            "path": {
                "type": "string",
                "required": False,
                "description": "Ruta relativa al vault (ej: 01_Projects/mi-api/overview.md)",
                "validators": ["within_vault"],
            },
            "title": {
                "type": "string",
                "required": False,
                "description": "Título de la nota a buscar",
                "validators": ["not_empty"],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": 'python vault_read.py --path "01_Projects/mi-api/overview.md"\npython vault_read.py --title "Overview"',
        "related": ["vault_write", "vault_search"],
    },
    "vault_search": {
        "name": "vault_search",
        "script": "vault_search.py",
        "group": "Core",
        "purpose": "Búsqueda full-text en search-index.json con score ponderado.",
        "params": {
            "query": {
                "type": "string",
                "required": True,
                "description": "Término de búsqueda",
                "validators": ["not_empty"],
            },
            "project": {
                "type": "string",
                "required": False,
                "description": "Filtrar por proyecto",
                "validators": [],
            },
            "folder": {
                "type": "string",
                "required": False,
                "description": "Filtrar por carpeta",
                "validators": [],
            },
            "limit": {
                "type": "int",
                "required": False,
                "description": "Límite de resultados (default: 10)",
                "validators": ["min:1", "max:100"],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": 'python vault_search.py --query "circuit breaker"\npython vault_search.py --query "deploy" --project "mi-api"',
        "related": ["vault_read", "vault_list"],
    },
    "vault_list": {
        "name": "vault_list",
        "script": "vault_list.py",
        "group": "Core",
        "purpose": "Lista notas de una carpeta del vault.",
        "params": {
            "folder": {
                "type": "string",
                "required": False,
                "description": "Carpeta a listar (sin vault root)",
                "validators": [],
            },
            "status": {
                "type": "string",
                "required": False,
                "description": "Filtrar por status",
                "validators": [],
            },
            "limit": {
                "type": "int",
                "required": False,
                "description": "Límite de resultados (default: 50)",
                "validators": ["min:1", "max:500"],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": 'python vault_list.py\npython vault_list.py --folder "01_Projects"',
        "related": ["vault_search", "vault_read"],
    },
    "vault_append": {
        "name": "vault_append",
        "script": "vault_append.py",
        "group": "Core",
        "purpose": "Agrega contenido al final de una nota existente (modo append-only).",
        "params": {
            "path": {
                "type": "string",
                "required": True,
                "description": "Ruta relativa de la nota",
                "validators": ["within_vault", "file_exists"],
            },
            "content": {
                "type": "string",
                "required": True,
                "description": "Contenido a agregar",
                "validators": ["not_empty"],
            },
            "section": {
                "type": "string",
                "required": False,
                "description": "Encabezado de sección donde agregar",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Versiona en .history/"],
        "example": 'python vault_append.py --path "01_Projects/mi-api/changelog.md" --content "## v1.2\\n\\nFix deploy"',
        "related": ["vault_write", "vault_read"],
    },
    "vault_diff": {
        "name": "vault_diff",
        "script": "vault_diff.py",
        "group": "Core",
        "purpose": "Muestra diferencias entre versiones de una nota.",
        "params": {
            "path": {
                "type": "string",
                "required": True,
                "description": "Ruta de la nota",
                "validators": ["within_vault"],
            },
            "version": {
                "type": "string",
                "required": False,
                "description": "Número de versión a comparar (default: última)",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": 'python vault_diff.py --path "01_Projects/mi-api/overview.md"',
        "related": ["vault_read", "vault_backup"],
    },
    "vault_merge": {
        "name": "vault_merge",
        "script": "vault_merge.py",
        "group": "Core",
        "purpose": "Detecta y resuelve duplicados entre vaults o dentro del mismo vault.",
        "params": {
            "action": {
                "type": "string",
                "required": True,
                "description": "Acción a realizar: detect, merge, dedup",
                "validators": ["enum:detect,merge,dedup"],
            },
            "source": {
                "type": "string",
                "required": False,
                "description": "Vault fuente para merge",
                "validators": ["path_exists"],
            },
            "conflict": {
                "type": "string",
                "required": False,
                "description": "Cómo resolver conflictos: skip, overwrite, keep_both",
                "validators": ["enum:skip,overwrite,keep_both"],
            },
        },
        "guards": [],
        "side_effects": ["Crea backups antes de modificar"],
        "example": 'python vault_merge.py --action detect\npython vault_merge.py --source "/path/to/other-vault" --action merge',
        "related": ["vault_backup", "vault_diff"],
    },
    "vault_log_error": {
        "name": "vault_log_error",
        "script": "vault_log_error.py",
        "group": "Observabilidad",
        "purpose": "Registra errores, antipatrones, vulnerabilidades, métricas, alertas y SLOs.",
        "params": {
            "type": {
                "type": "string",
                "required": True,
                "description": "Tipo: error, antipattern, vulnerability, metric, alert, slo",
                "validators": [
                    "enum:error,antipattern,vulnerability,waf,metric,alert,slo"
                ],
            },
            "title": {
                "type": "string",
                "required": True,
                "description": "Título descriptivo",
                "validators": ["not_empty", "max_length:200"],
            },
            "description": {
                "type": "string",
                "required": True,
                "description": "Descripción detallada",
                "validators": ["min_length:10"],
            },
            "severity": {
                "type": "string",
                "required": True,
                "description": "Severidad: critical, high, medium, low, info",
                "validators": ["enum:critical,high,medium,low,info"],
            },
            "project": {
                "type": "string",
                "required": False,
                "description": "Proyecto relacionado",
                "validators": [],
            },
            "meta": {
                "type": "json",
                "required": False,
                "description": "Metadatos adicionales",
                "validators": ["valid_json"],
            },
        },
        "guards": [],
        "side_effects": ["Crea/actualiza nota en 02_Observability/"],
        "example": 'python vault_log_error.py --type error --title "NullPointerException" --description "..." --severity high',
        "related": ["vault_audit", "vault_drift_detect", "vault_impact"],
    },
    "vault_audit": {
        "name": "vault_audit",
        "script": "vault_audit.py",
        "group": "Salud del Vault",
        "purpose": "Evalúa health score del vault y genera nextActions.",
        "params": {
            "project": {
                "type": "string",
                "required": False,
                "description": "Proyecto a auditar",
                "validators": [],
            },
            "refresh-dq": {
                "type": "boolean",
                "required": False,
                "description": "Forzar refresh de Data Quality",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": 'python vault_audit.py\npython vault_audit.py --project "mi-proyecto"',
        "related": ["vault_validate", "vault_fix_brackets", "vault_quality_check"],
    },
    "vault_validate": {
        "name": "vault_validate",
        "script": "vault_validate.py",
        "group": "Salud del Vault",
        "purpose": "Valida notas contra el schema y normas del vault.",
        "params": {
            "path": {
                "type": "string",
                "required": False,
                "description": "Ruta de nota a validar",
                "validators": ["within_vault"],
            },
            "folder": {
                "type": "string",
                "required": False,
                "description": "Carpeta a validar",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": 'python vault_validate.py --path "01_Projects/mi-api/overview.md"',
        "related": ["vault_audit", "vault_write"],
    },
    "vault_fix_brackets": {
        "name": "vault_fix_brackets",
        "script": "vault_fix_brackets.py",
        "group": "Corrección Automática",
        "purpose": "Detecta y corrige anomalías de corchetes en wiki-links (AP-22, AP-24).",
        "params": {
            "path": {
                "type": "string",
                "required": False,
                "description": "Procesar solo esta nota",
                "validators": ["within_vault"],
            },
            "apply": {
                "type": "boolean",
                "required": False,
                "description": "Aplicar fixes (default: dry-run)",
                "validators": [],
            },
            "only": {
                "type": "string",
                "required": False,
                "description": "Filtrar por tipo: empty, nested",
                "validators": ["enum:empty,nested"],
            },
        },
        "guards": [],
        "side_effects": ["Backups en .vault-fix-backup-YYYYMMDD/"],
        "example": 'python vault_fix_brackets.py\npython vault_fix_brackets.py --apply\npython vault_fix_brackets.py --path "02_Observability/errors/foo.md"',
        "related": ["vault_audit", "vault_regex"],
    },
    "vault_delta": {
        "name": "vault_delta",
        "script": "vault_delta.py",
        "group": "Session Delta y Tags",
        "purpose": "Detecta cambios entre sesiones usando SHA-256 y BFS sobre grafo de backlinks.",
        "params": {
            "snapshot": {
                "type": "boolean",
                "required": False,
                "description": "Guardar snapshot actual",
                "validators": [],
            }
        },
        "guards": [],
        "side_effects": ["Crea 00_System/delta-snapshot.json"],
        "example": "python vault_delta.py --snapshot\npython vault_delta.py",
        "related": ["vault_tags", "vault_reindex", "vault_drift_detect"],
    },
    "vault_tags": {
        "name": "vault_tags",
        "script": "vault_tags.py",
        "group": "Session Delta y Tags",
        "purpose": "Registro canónico de tags, auditoría de orphans y near-dupes.",
        "params": {
            "action": {
                "type": "string",
                "required": False,
                "description": "Acción: list, suggest",
                "validators": ["enum:list,suggest"],
            },
            "tag": {
                "type": "string",
                "required": False,
                "description": "Tag a analizar",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": "python vault_tags.py --action list",
        "related": ["vault_delta", "vault_audit"],
    },
    "vault_reindex": {
        "name": "vault_reindex",
        "script": "vault_reindex.py",
        "group": "Índices",
        "purpose": "Actualiza search-index.json y opcionalmente hash-index.json.",
        "params": {
            "graph": {
                "type": "boolean",
                "required": False,
                "description": "También generar graph.json",
                "validators": [],
            },
            "hash": {
                "type": "boolean",
                "required": False,
                "description": "También generar hash-index.json",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": [
            "Actualiza 99_Index/search-index.json",
            "Opcional: 99_Index/graph.json, hash-index.json",
        ],
        "example": "python vault_reindex.py\npython vault_reindex.py --graph --hash",
        "related": ["vault_search", "vault_graph"],
    },
    "vault_graph": {
        "name": "vault_graph",
        "script": "vault_graph.py",
        "group": "Salud del Vault",
        "purpose": "Genera grafo de relaciones entre notas.",
        "params": {
            "project": {
                "type": "string",
                "required": False,
                "description": "Proyecto específico",
                "validators": [],
            }
        },
        "guards": [],
        "side_effects": ["Crea 99_Index/graph.json"],
        "example": 'python vault_graph.py\npython vault_graph.py --project "mi-api"',
        "related": ["vault_audit", "vault_impact", "vault_propagate"],
    },
    "vault_init": {
        "name": "vault_init",
        "script": "vault_init.py",
        "group": "Bootstrap",
        "purpose": "Bootstrap de vault nuevo en un comando.",
        "params": {
            "target": {
                "type": "string",
                "required": False,
                "description": "Versión objetivo (default: v34)",
                "validators": [],
            },
            "no-audit": {
                "type": "boolean",
                "required": False,
                "description": "No ejecutar vault_audit al final",
                "validators": [],
            },
            "clean": {
                "type": "boolean",
                "required": False,
                "description": "Borrar contenido existente (DANGEROUS)",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Crea carpetas, versiona, indexa, audit"],
        "example": "python vault_init.py\npython vault_init.py --target v34",
        "related": ["vault_standard_upgrade", "vault_audit"],
    },
    "vault_standard_upgrade": {
        "name": "vault_standard_upgrade",
        "script": "vault_standard_upgrade.py",
        "group": "Versionado",
        "purpose": "Detecta y aplica migraciones entre versiones del estándar.",
        "params": {
            "from": {
                "type": "string",
                "required": False,
                "description": "Versión actual (lee standard-version.json si se omite)",
                "validators": [],
            },
            "to": {
                "type": "string",
                "required": False,
                "description": "Versión objetivo (default: v34)",
                "validators": [],
            },
            "check": {
                "type": "boolean",
                "required": False,
                "description": "Solo reportar sin aplicar",
                "validators": [],
            },
            "init": {
                "type": "string",
                "required": False,
                "description": "Inicializar archivo de versión",
                "validators": [],
            },
            "fixes-only": {
                "type": "boolean",
                "required": False,
                "description": "Solo ejecutar fixes sin migrar",
                "validators": [],
            },
            "dry-run": {
                "type": "boolean",
                "required": False,
                "description": "Simular sin aplicar cambios",
                "validators": [],
            },
            "report": {
                "type": "boolean",
                "required": False,
                "description": "Generar reporte de fixes disponibles",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": [
            "Actualiza 00_System/standard-version.json",
            "Ejecuta fixes automáticos",
        ],
        "example": "python vault_standard_upgrade.py --check\npython vault_standard_upgrade.py --to v34\npython vault_standard_upgrade.py --report",
        "related": ["vault_init", "vault_audit"],
    },
    "vault_move": {
        "name": "vault_move",
        "script": "vault_move.py",
        "group": "Core",
        "purpose": "Reubica notas entre carpetas del vault, actualiza wiki-links, índices y grafo.",
        "params": {
            "from": {
                "type": "string",
                "required": False,
                "description": "Nota origen",
                "validators": ["within_vault"],
            },
            "to": {
                "type": "string",
                "required": False,
                "description": "Nota destino",
                "validators": [],
            },
            "folder": {
                "type": "string",
                "required": False,
                "description": "Carpeta origen (mover toda)",
                "validators": [],
            },
            "to-folder": {
                "type": "string",
                "required": False,
                "description": "Carpeta destino",
                "validators": [],
            },
            "dry_run": {
                "type": "boolean",
                "required": False,
                "description": "Simular sin aplicar",
                "validators": [],
            },
            "impact": {
                "type": "boolean",
                "required": False,
                "description": "Analizar impacto sin ejecutar",
                "validators": [],
            },
        },
        "guards": ["Confimar antes de sobreescribir"],
        "side_effects": ["Actualiza wiki-links, search-index, graph.json, move-log"],
        "example": 'python vault_move.py --from "01_Projects/foo.md" --to "03_Decisions/foo.md"\npython vault_move.py --folder "01_Projects/old" --to_folder "01_Projects/new"',
        "related": ["vault_write", "vault_graph", "vault_reindex"],
    },
    "vault_folder_registry": {
        "name": "vault_folder_registry",
        "script": "vault_folder_registry.py",
        "group": "Gestión de Carpetas",
        "purpose": "Auto-detecta y registra carpetas personalizadas dentro de secciones del vault.",
        "params": {
            "scan": {
                "type": "boolean",
                "required": False,
                "description": "Escanear carpetas nuevas",
                "validators": [],
            },
            "list": {
                "type": "boolean",
                "required": False,
                "description": "Listar carpetas",
                "validators": [],
            },
            "add": {
                "type": "string",
                "required": False,
                "description": "Agregar carpeta manualmente",
                "validators": [],
            },
            "remove": {
                "type": "string",
                "required": False,
                "description": "Eliminar carpeta del registro",
                "validators": [],
            },
            "cleanup": {
                "type": "boolean",
                "required": False,
                "description": "Limpiar carpetas huérfanas",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Crea/actualiza 00_System/custom-folders.json"],
        "example": 'python vault_folder_registry.py\npython vault_folder_registry.py --scan\npython vault_folder_registry.py --add "11_Code/tests"',
        "related": ["vault_reindex", "vault_audit"],
    },
    "vault_mermaid_check": {
        "name": "vault_mermaid_check",
        "script": "vault_mermaid_check.py",
        "group": "Diagramas",
        "purpose": "Valida diagramas Mermaid y detecta errores de sintaxis.",
        "params": {
            "path": {
                "type": "string",
                "required": False,
                "description": "Archivo específico",
                "validators": ["within_vault"],
            },
            "project": {
                "type": "string",
                "required": False,
                "description": "Proyecto a verificar",
                "validators": [],
            },
            "fix": {
                "type": "boolean",
                "required": False,
                "description": "Auto-corregir errores",
                "validators": [],
            },
            "json": {
                "type": "boolean",
                "required": False,
                "description": "Salida JSON",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": 'python vault_mermaid_check.py\npython vault_mermaid_check.py --path "06_Diagrams/foo.md"\npython vault_mermaid_check.py --fix',
        "related": ["vault_diagram_save", "vault_render", "vault_write"],
    },
    "vault_diagram_export": {
        "name": "vault_diagram_export",
        "script": "vault_diagram_export.py",
        "group": "Diagramas",
        "purpose": "Exporta diagramas con opciones de zoom, pan y filtros.",
        "params": {
            "path": {
                "type": "string",
                "required": False,
                "description": "Archivo a exportar",
                "validators": ["within_vault"],
            },
            "project": {
                "type": "string",
                "required": False,
                "description": "Proyecto a exportar",
                "validators": [],
            },
            "output": {
                "type": "string",
                "required": False,
                "description": "Carpeta de salida",
                "validators": [],
            },
            "zoom": {
                "type": "float",
                "required": False,
                "description": "Nivel de zoom (default: 1.0)",
                "validators": [],
            },
            "pan_x": {
                "type": "int",
                "required": False,
                "description": "Posición X del pan",
                "validators": [],
            },
            "pan_y": {
                "type": "int",
                "required": False,
                "description": "Posición Y del pan",
                "validators": [],
            },
            "filter": {
                "type": "string",
                "required": False,
                "description": "Filtrar por tipo",
                "validators": [],
            },
            "highlight": {
                "type": "string",
                "required": False,
                "description": "Nodos a resaltar (coma)",
                "validators": [],
            },
            "hide": {
                "type": "string",
                "required": False,
                "description": "Nodos a ocultar (coma)",
                "validators": [],
            },
            "config": {
                "type": "boolean",
                "required": False,
                "description": "Guardar configuración global",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Genera archivos exportados"],
        "example": 'python vault_diagram_export.py --path "06_Diagrams/foo.md" --zoom 2.0\npython vault_diagram_export.py --project "mi-api" --output "export/"',
        "related": ["vault_diagram_save", "vault_mermaid_check"],
    },
    "vault_diagram_save": {
        "name": "vault_diagram_save",
        "script": "vault_diagram_save.py",
        "group": "Diagramas",
        "purpose": "Guarda diagramas Mermaid/ASCII/PlantUML con frontmatter categorizado.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto relacionado",
                "validators": [],
            },
            "title": {
                "type": "string",
                "required": True,
                "description": "Título del diagrama",
                "validators": ["not_empty"],
            },
            "diagram_type": {
                "type": "string",
                "required": True,
                "description": "Tipo: mermaid, ascii, plantuml",
                "validators": ["enum:mermaid,ascii,plantuml"],
            },
            "category": {
                "type": "string",
                "required": True,
                "description": "Categoría: entity, component, sequence, dependency, flow, state, lifecycle",
                "validators": [
                    "enum:entity,component,sequence,dependency,flow,state,lifecycle"
                ],
            },
            "content": {
                "type": "string",
                "required": True,
                "description": "Contenido del diagrama (sin backticks)",
                "validators": [],
            },
            "description": {
                "type": "string",
                "required": False,
                "description": "Descripción opcional",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Crea nota en 06_Diagrams/{category}/"],
        "example": 'python vault_diagram_save.py --project "mi-api" --title "User Flow" --diagram_type "mermaid" --category "flow" --content "graph TD\\n  A --> B"',
        "related": ["vault_relation_add", "vault_render", "vault_graph"],
    },
    "vault_relation_add": {
        "name": "vault_relation_add",
        "script": "vault_relation_add.py",
        "group": "Diagramas",
        "purpose": "Agrega relaciones entre entidades y genera ERD automático.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "entity": {
                "type": "string",
                "required": True,
                "description": "Entidad origen",
                "validators": ["not_empty"],
            },
            "to": {
                "type": "string",
                "required": True,
                "description": "Entidad destino",
                "validators": ["not_empty"],
            },
            "type": {
                "type": "string",
                "required": True,
                "description": "Tipo: one-to-one, one-to-many, many-to-many",
                "validators": ["enum:one-to-one,one-to-many,many-to-many"],
            },
            "label": {
                "type": "string",
                "required": False,
                "description": "Etiqueta de la relación",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Actualiza relaciones en 07_Knowledge/"],
        "example": 'python vault_relation_add.py --project "mi-api" --entity "User" --to "Order" --type "one-to-many"',
        "related": ["vault_diagram_save", "vault_code_relation"],
    },
    "vault_code_module": {
        "name": "vault_code_module",
        "script": "vault_code_module.py",
        "group": "Código",
        "purpose": "Genera templates de módulos de código con IEEE 1016.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "module": {
                "type": "string",
                "required": True,
                "description": "Nombre del módulo",
                "validators": ["not_empty"],
            },
            "language": {
                "type": "string",
                "required": True,
                "description": "Lenguaje: python, javascript, typescript, go, rust",
                "validators": ["enum:python,javascript,typescript,go,rust"],
            },
            "viewpoints": {
                "type": "string",
                "required": False,
                "description": "Viewpoints IEEE 1016: context,interface,data,operations,dependency",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Crea nota en 11_Code/{project}/"],
        "example": 'python vault_code_module.py --project "mi-api" --module "auth" --language "python" --viewpoints "context,interface"',
        "related": ["vault_code_map", "vault_code_relation", "vault_diagram_save"],
    },
    "vault_code_map": {
        "name": "vault_code_map",
        "script": "vault_code_map.py",
        "group": "Código",
        "purpose": "Genera mapa de dependencias entre módulos de código.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "depth": {
                "type": "int",
                "required": False,
                "description": "Profundidad máxima (default: 3)",
                "validators": ["min:1", "max:10"],
            },
        },
        "guards": [],
        "side_effects": ["Genera 11_Code/{project}/map.md con diagrama"],
        "example": 'python vault_code_map.py --project "mi-api"\npython vault_code_map.py --project "mi-api" --depth 2',
        "related": ["vault_code_module", "vault_code_relation", "vault_graph"],
    },
    "vault_code_relation": {
        "name": "vault_code_relation",
        "script": "vault_code_relation.py",
        "group": "Código",
        "purpose": "Registra y visualiza relaciones entre componentes de código.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "from": {
                "type": "string",
                "required": True,
                "description": "Componente origen",
                "validators": [],
            },
            "to": {
                "type": "string",
                "required": True,
                "description": "Componente destino",
                "validators": [],
            },
            "type": {
                "type": "string",
                "required": True,
                "description": "Tipo: imports,calls,extends,implements,depends",
                "validators": ["enum:imports,calls,extends,implements,depends"],
            },
        },
        "guards": [],
        "side_effects": ["Actualiza índice de relaciones en 11_Code/"],
        "example": 'python vault_code_relation.py --project "mi-api" --from "auth.py" --to "user.py" --type "imports"',
        "related": ["vault_code_map", "vault_code_module"],
    },
    "vault_code_query": {
        "name": "vault_code_query",
        "script": "vault_code_query.py",
        "group": "Código",
        "purpose": "Consulta información del índice de código.",
        "params": {
            "query": {
                "type": "string",
                "required": True,
                "description": "Consulta: module, relation, imports",
                "validators": ["enum:module,relation,imports"],
            },
            "project": {
                "type": "string",
                "required": False,
                "description": "Filtrar por proyecto",
                "validators": [],
            },
            "pattern": {
                "type": "string",
                "required": False,
                "description": "Patrón de búsqueda",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": 'python vault_code_query.py --query "module" --project "mi-api"\npython vault_code_query.py --query "imports" --pattern "auth"',
        "related": ["vault_code_map", "vault_search"],
    },
    "vault_code_sync": {
        "name": "vault_code_sync",
        "script": "vault_code_sync.py",
        "group": "Código",
        "purpose": "Sincroniza estado del código con el vault.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "action": {
                "type": "string",
                "required": True,
                "description": "Acción: scan, update, diff",
                "validators": ["enum:scan,update,diff"],
            },
        },
        "guards": [],
        "side_effects": ["Actualiza 11_Code/{project}/index.json"],
        "example": 'python vault_code_sync.py --project "mi-api" --action "scan"\npython vault_code_sync.py --project "mi-api" --action "update"',
        "related": ["vault_code_map", "vault_reindex"],
    },
    "vault_code_tag": {
        "name": "vault_code_tag",
        "script": "vault_code_tag.py",
        "group": "Código",
        "purpose": "Etiqueta módulos de código por funcionalidad.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "module": {
                "type": "string",
                "required": True,
                "description": "Módulo a etiquetar",
                "validators": [],
            },
            "tags": {
                "type": "string",
                "required": True,
                "description": "Tags separados por coma",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Actualiza frontmatter del módulo"],
        "example": 'python vault_code_tag.py --project "mi-api" --module "auth" --tags "security,auth,api"',
        "related": ["vault_tags", "vault_code_module"],
    },
    "vault_flow_save": {
        "name": "vault_flow_save",
        "script": "vault_flow_save.py",
        "group": "Flujos",
        "purpose": "Guarda workflows, pipelines, lifecycles y dataflows con diagrama Mermaid.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "name": {
                "type": "string",
                "required": True,
                "description": "Nombre del flujo",
                "validators": ["not_empty"],
            },
            "type": {
                "type": "string",
                "required": True,
                "description": "Tipo: workflow, pipeline, lifecycle, dataflow",
                "validators": ["enum:workflow,pipeline,lifecycle,dataflow"],
            },
            "description": {
                "type": "string",
                "required": True,
                "description": "Descripción",
                "validators": ["min_length:10"],
            },
            "mermaid": {
                "type": "string",
                "required": True,
                "description": "Diagrama Mermaid (sin backticks)",
                "validators": [],
            },
            "actors": {
                "type": "string",
                "required": False,
                "description": "Actores separados por coma",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Crea nota en 13_Flows/{type}/"],
        "example": 'python vault_flow_save.py --project "mi-api" --name "User Registration" --type workflow --description "Full process" --mermaid "flowchart TD\\n  A --> B"',
        "related": ["vault_diagram_save", "vault_graph"],
    },
    "vault_pattern_save": {
        "name": "vault_pattern_save",
        "script": "vault_pattern_save.py",
        "group": "Patrones",
        "purpose": "Guarda patrones arquitectónicos en el vault.",
        "params": {
            "name": {
                "type": "string",
                "required": True,
                "description": "Nombre del patrón",
                "validators": ["not_empty"],
            },
            "category": {
                "type": "string",
                "required": True,
                "description": "Categoría: creational, structural, behavioral, architectural",
                "validators": ["enum:creational,structural,behavioral,architectural"],
            },
            "description": {
                "type": "string",
                "required": True,
                "description": "Descripción del patrón",
                "validators": ["min_length:20"],
            },
            "implementation": {
                "type": "string",
                "required": False,
                "description": "Código de ejemplo",
                "validators": [],
            },
            "use_cases": {
                "type": "string",
                "required": False,
                "description": "Casos de uso separados por coma",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Crea nota en 05_Patterns/"],
        "example": 'python vault_pattern_save.py --name "Repository" --category "architectural" --description "Data access abstraction" --use_cases "database,cache',
        "related": ["vault_pattern_list", "vault_code_module"],
    },
    "vault_pattern_list": {
        "name": "vault_pattern_list",
        "script": "vault_pattern_list.py",
        "group": "Patrones",
        "purpose": "Lista patrones arquitectónicos disponibles.",
        "params": {
            "category": {
                "type": "string",
                "required": False,
                "description": "Filtrar por categoría",
                "validators": ["enum:creational,structural,behavioral,architectural"],
            },
            "search": {
                "type": "string",
                "required": False,
                "description": "Buscar por nombre",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": 'python vault_pattern_list.py\npython vault_pattern_list.py --category "architectural"',
        "related": ["vault_pattern_save", "vault_search"],
    },
    "vault_knowledge_save": {
        "name": "vault_knowledge_save",
        "script": "vault_knowledge_save.py",
        "group": "Conocimiento",
        "purpose": "Guarda conocimiento estructurado por tema.",
        "params": {
            "topic": {
                "type": "string",
                "required": True,
                "description": "Tema principal",
                "validators": ["not_empty"],
            },
            "title": {
                "type": "string",
                "required": True,
                "description": "Título del conocimiento",
                "validators": ["not_empty"],
            },
            "content": {
                "type": "string",
                "required": True,
                "description": "Contenido estructurado",
                "validators": ["min_lines:3"],
            },
            "tags": {
                "type": "string",
                "required": False,
                "description": "Tags separados por espacio",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Crea nota en 07_Knowledge/{topic}/"],
        "example": 'python vault_knowledge_save.py --topic "architecture" --title "Clean Architecture" --content "# Clean Architecture\\n\\nLayers..." --tags "architecture clean',
        "related": ["vault_knowledge_get", "vault_search"],
    },
    "vault_knowledge_get": {
        "name": "vault_knowledge_get",
        "script": "vault_knowledge_get.py",
        "group": "Conocimiento",
        "purpose": "Recupera conocimiento por tema o búsqueda.",
        "params": {
            "topic": {
                "type": "string",
                "required": False,
                "description": "Tema a buscar",
                "validators": [],
            },
            "query": {
                "type": "string",
                "required": False,
                "description": "Palabra clave",
                "validators": [],
            },
            "limit": {
                "type": "int",
                "required": False,
                "description": "Límite de resultados (default: 10)",
                "validators": ["min:1", "max:50"],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": 'python vault_knowledge_get.py --topic "architecture"\npython vault_knowledge_get.py --query "clean"',
        "related": ["vault_knowledge_save", "vault_search"],
    },
    "vault_backup": {
        "name": "vault_backup",
        "script": "vault_backup.py",
        "group": "Backups",
        "purpose": "Crea backup del vault en carpeta timestamped.",
        "params": {
            "include_history": {
                "type": "boolean",
                "required": False,
                "description": "Incluir .history/ (default: False)",
                "validators": [],
            },
            "compress": {
                "type": "boolean",
                "required": False,
                "description": "Comprimir a zip (default: False)",
                "validators": [],
            },
            "label": {
                "type": "string",
                "required": False,
                "description": "Etiqueta opcional",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Crea carpeta en vault-backups/"],
        "example": 'python vault_backup.py\npython vault_backup.py --compress --label "pre-migration"',
        "related": ["vault_backup_list", "vault_restore"],
    },
    "vault_backup_list": {
        "name": "vault_backup_list",
        "script": "vault_backup_list.py",
        "group": "Backups",
        "purpose": "Lista backups disponibles.",
        "params": {
            "limit": {
                "type": "int",
                "required": False,
                "description": "Cantidad máxima (default: 20)",
                "validators": ["min:1", "max:100"],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": "python vault_backup_list.py\npython vault_backup_list.py --limit 5",
        "related": ["vault_backup", "vault_restore"],
    },
    "vault_restore": {
        "name": "vault_restore",
        "script": "vault_restore.py",
        "group": "Backups",
        "purpose": "Restaura vault desde backup.",
        "params": {
            "backup_id": {
                "type": "string",
                "required": True,
                "description": "ID del backup a restaurar",
                "validators": [],
            },
            "target": {
                "type": "string",
                "required": False,
                "description": "Carpeta destino (default: VAULT_ROOT)",
                "validators": [],
            },
            "dry_run": {
                "type": "boolean",
                "required": False,
                "description": "Simular sin aplicar",
                "validators": [],
            },
        },
        "guards": ["Confirmar antes de sobreescribir"],
        "side_effects": ["Sobreescribe archivos del vault"],
        "example": 'python vault_restore.py --backup_id "2026-06-24_120000"\npython vault_restore.py --backup_id "2026-06-24_120000" --dry_run',
        "related": ["vault_backup", "vault_backup_list"],
    },
    "vault_env_save": {
        "name": "vault_env_save",
        "script": "vault_env_save.py",
        "group": "Infraestructura",
        "purpose": "Guarda variables de entorno y secretos para un proyecto.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "environment": {
                "type": "string",
                "required": True,
                "description": "Entorno: dev, staging, prod",
                "validators": ["enum:dev,staging,prod"],
            },
            "variables": {
                "type": "string",
                "required": True,
                "description": "Variables en formato KEY=VALUE separadas por espacio",
                "validators": [],
            },
        },
        "guards": ["No guardar secrets en texto plano"],
        "side_effects": ["Crea nota en 09_Infrastructure/{project}/"],
        "example": 'python vault_env_save.py --project "mi-api" --environment "prod" --variables "DB_HOST=localhost API_KEY=xxx"',
        "related": ["vault_env_matrix", "vault_infra_save"],
    },
    "vault_env_matrix": {
        "name": "vault_env_matrix",
        "script": "vault_env_matrix.py",
        "group": "Infraestructura",
        "purpose": "Genera matriz comparativa de entornos.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Genera 09_Infrastructure/{project}/matrix.md"],
        "example": 'python vault_env_matrix.py --project "mi-api"',
        "related": ["vault_env_save", "vault_infra_map"],
    },
    "vault_infra_save": {
        "name": "vault_infra_save",
        "script": "vault_infra_save.py",
        "group": "Infraestructura",
        "purpose": "Guarda documentación de infraestructura.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "title": {
                "type": "string",
                "required": True,
                "description": "Título",
                "validators": ["not_empty"],
            },
            "provider": {
                "type": "string",
                "required": True,
                "description": "Proveedor: aws, gcp, azure, onprem",
                "validators": ["enum:aws,gcp,azure,onprem"],
            },
            "components": {
                "type": "string",
                "required": True,
                "description": "Componentes separados por coma",
                "validators": [],
            },
            "description": {
                "type": "string",
                "required": False,
                "description": "Descripción",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Crea nota en 09_Infrastructure/{project}/"],
        "example": 'python vault_infra_save.py --project "mi-api" --title "Production" --provider "aws" --components "EC2,RDS,S3"',
        "related": ["vault_infra_map", "vault_env_save"],
    },
    "vault_infra_map": {
        "name": "vault_infra_map",
        "script": "vault_infra_map.py",
        "group": "Infraestructura",
        "purpose": "Genera mapa visual de infraestructura en Mermaid.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "components": {
                "type": "string",
                "required": True,
                "description": "Componentes separados por coma",
                "validators": [],
            },
            "location": {
                "type": "string",
                "required": False,
                "description": "Ubicación geográfica",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Genera diagrama en 09_Infrastructure/{project}/"],
        "example": 'python vault_infra_map.py --project "mi-api" --components "EC2,RDS,S3" --location "us-east-1"',
        "related": ["vault_infra_save", "vault_diagram_save"],
    },
    "vault_security_scan": {
        "name": "vault_security_scan",
        "script": "vault_security_scan.py",
        "group": "Seguridad",
        "purpose": "Escaneo de seguridad del vault y código.",
        "params": {
            "project": {
                "type": "string",
                "required": False,
                "description": "Proyecto específico",
                "validators": [],
            },
            "scan_type": {
                "type": "string",
                "required": False,
                "description": "Tipo: full, secrets, dependencies",
                "validators": ["enum:full,secrets,dependencies"],
            },
        },
        "guards": [],
        "side_effects": ["Genera reporte en 02_Observability/security/"],
        "example": 'python vault_security_scan.py\npython vault_security_scan.py --project "mi-api" --scan_type "secrets"',
        "related": ["vault_audit", "vault_log_error"],
    },
    "vault_drift_detect": {
        "name": "vault_drift_detect",
        "script": "vault_drift_detect.py",
        "group": "Drift Detection",
        "purpose": "Detecta drift de configuración entre ambientes.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "compare": {
                "type": "string",
                "required": True,
                "description": "Entornos a comparar: dev-staging, staging-prod",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Reporta drift detectado"],
        "example": 'python vault_drift_detect.py --project "mi-api" --compare "dev-staging"',
        "related": ["vault_audit", "vault_env_matrix"],
    },
    "vault_impact": {
        "name": "vault_impact",
        "script": "vault_impact.py",
        "group": "Propagación",
        "purpose": "Análisis de impacto en cascada de cambios.",
        "params": {
            "path": {
                "type": "string",
                "required": True,
                "description": "Nota a analizar",
                "validators": ["within_vault"],
            },
            "depth": {
                "type": "int",
                "required": False,
                "description": "Profundidad máxima (default: 3)",
                "validators": ["min:1", "max:10"],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": 'python vault_impact.py --path "01_Projects/mi-api/overview.md"\npython vault_impact.py --path "01_Projects/mi-api/overview.md" --depth 5',
        "related": ["vault_propagate", "vault_graph"],
    },
    "vault_propagate": {
        "name": "vault_propagate",
        "script": "vault_propagate.py",
        "group": "Propagación",
        "purpose": "Propaga cambios entre notas relacionadas.",
        "params": {
            "source": {
                "type": "string",
                "required": True,
                "description": "Nota fuente",
                "validators": ["within_vault"],
            },
            "template": {
                "type": "string",
                "required": True,
                "description": "Template de propagación",
                "validators": [],
            },
            "dry_run": {
                "type": "boolean",
                "required": False,
                "description": "Simular sin aplicar",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Actualiza notas relacionadas"],
        "example": 'python vault_propagate.py --source "01_Projects/mi-api/overview.md" --template "Updated: {title}"',
        "related": ["vault_impact", "vault_write"],
    },
    "vault_quality_check": {
        "name": "vault_quality_check",
        "script": "vault_quality_check.py",
        "group": "Data Quality",
        "purpose": "Verifica calidad de datos del vault.",
        "params": {
            "project": {
                "type": "string",
                "required": False,
                "description": "Proyecto específico",
                "validators": [],
            },
            "metrics": {
                "type": "string",
                "required": False,
                "description": "Métricas: completeness,consistency,accuracy",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Genera reporte en 00_System/"],
        "example": 'python vault_quality_check.py\npython vault_quality_check.py --project "mi-api" --metrics "completeness"',
        "related": ["vault_audit", "vault_fundamentals"],
    },
    "vault_fundamentals": {
        "name": "vault_fundamentals",
        "script": "vault_fundamentals.py",
        "group": "Data Quality",
        "purpose": "Métricas fundamentales del vault.",
        "params": {},
        "guards": [],
        "side_effects": [],
        "example": "python vault_fundamentals.py",
        "related": ["vault_audit", "vault_quality_check"],
    },
    "vault_project_status": {
        "name": "vault_project_status",
        "script": "vault_project_status.py",
        "group": "Vista del Proyecto",
        "purpose": "Muestra estado actual de un proyecto.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Slug del proyecto",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": 'python vault_project_status.py --project "mi-api"',
        "related": ["vault_project_overview", "vault_audit"],
    },
    "vault_project_overview": {
        "name": "vault_project_overview",
        "script": "vault_project_overview.py",
        "group": "Vista del Proyecto",
        "purpose": "Genera overview consolidado de proyecto.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Slug del proyecto",
                "validators": [],
            },
            "description": {
                "type": "string",
                "required": False,
                "description": "Descripción del proyecto",
                "validators": [],
            },
            "runtime": {
                "type": "string",
                "required": False,
                "description": "Runtime (ej: Node.js 20)",
                "validators": [],
            },
            "extra_sections": {
                "type": "string",
                "required": False,
                "description": "Secciones extra en JSON",
                "validators": ["valid_json"],
            },
        },
        "guards": [],
        "side_effects": ["Crea/actualiza 01_Projects/{slug}/overview.md"],
        "example": 'python vault_project_overview.py --project "mi-api" --description "REST API" --runtime "Node.js 20"',
        "related": ["vault_project_status", "vault_audit"],
    },
    "vault_section_index": {
        "name": "vault_section_index",
        "script": "vault_section_index.py",
        "group": "Índices",
        "purpose": "Genera índice de una sección del vault.",
        "params": {
            "section": {
                "type": "string",
                "required": True,
                "description": "Sección (ej: 01_Projects)",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Genera {section}/index.md"],
        "example": 'python vault_section_index.py --section "01_Projects"',
        "related": ["vault_master_index", "vault_reindex"],
    },
    "vault_master_index": {
        "name": "vault_master_index",
        "script": "vault_master_index.py",
        "group": "Índices",
        "purpose": "Genera índice maestro del vault.",
        "params": {
            "include_subdirs": {
                "type": "boolean",
                "required": False,
                "description": "Incluir subdirectorios",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Genera 99_Index/master-index.md"],
        "example": "python vault_master_index.py\npython vault_master_index.py --include_subdirs",
        "related": ["vault_section_index", "vault_reindex"],
    },
    "vault_timeline": {
        "name": "vault_timeline",
        "script": "vault_timeline.py",
        "group": "Línea de Tiempo",
        "purpose": "Genera línea temporal de eventos del vault.",
        "params": {
            "project": {
                "type": "string",
                "required": False,
                "description": "Filtrar por proyecto",
                "validators": [],
            },
            "days": {
                "type": "int",
                "required": False,
                "description": "Días hacia atrás (default: 30)",
                "validators": ["min:1", "max:365"],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": "python vault_timeline.py\npython vault_timeline.py --days 7",
        "related": ["vault_audit", "vault_change_log"],
    },
    "vault_change_log": {
        "name": "vault_change_log",
        "script": "vault_change_log.py",
        "group": "Change Log",
        "purpose": "Genera registro de cambios del vault.",
        "params": {
            "project": {
                "type": "string",
                "required": False,
                "description": "Proyecto específico",
                "validators": [],
            },
            "from": {
                "type": "string",
                "required": False,
                "description": "Desde fecha (YYYY-MM-DD)",
                "validators": [],
            },
            "to": {
                "type": "string",
                "required": False,
                "description": "Hasta fecha (YYYY-MM-DD)",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": 'python vault_change_log.py\npython vault_change_log.py --project "mi-api" --from "2026-01-01"',
        "related": ["vault_timeline", "vault_audit"],
    },
    "vault_ai_decision": {
        "name": "vault_ai_decision",
        "script": "vault_ai_decision.py",
        "group": "IA Governance",
        "purpose": "Registra decisiones de IA del proyecto.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "decision": {
                "type": "string",
                "required": True,
                "description": "Decisión tomada",
                "validators": ["not_empty"],
            },
            "rationale": {
                "type": "string",
                "required": True,
                "description": "Razón de la decisión",
                "validators": ["min_length:20"],
            },
            "alternatives": {
                "type": "string",
                "required": False,
                "description": "Alternativas consideradas",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Crea nota en 03_Decisions/"],
        "example": 'python vault_ai_decision.py --project "mi-api" --decision "Use PostgreSQL" --rationale "ACID compliance"',
        "related": ["vault_norms", "vault_audit"],
    },
    "vault_norms": {
        "name": "vault_norms",
        "script": "vault_norms.py",
        "group": "Normas",
        "purpose": "Gestiona normas y estándares del vault.",
        "params": {
            "action": {
                "type": "string",
                "required": True,
                "description": "Acción: list, add, check",
                "validators": ["enum:list,add,check"],
            },
            "name": {
                "type": "string",
                "required": False,
                "description": "Nombre de la norma",
                "validators": [],
            },
            "content": {
                "type": "string",
                "required": False,
                "description": "Contenido de la norma",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": 'python vault_norms.py --action "list"\npython vault_norms.py --action "add" --name "AP-25" --content "Code style rules"',
        "related": ["vault_ai_decision", "vault_audit"],
    },
    "vault_tokens": {
        "name": "vault_tokens",
        "script": "vault_tokens.py",
        "group": "Tokens",
        "purpose": "Gestión de tokens del proyecto.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "action": {
                "type": "string",
                "required": True,
                "description": "Acción: list, add, remove",
                "validators": ["enum:list,add,remove"],
            },
            "token_type": {
                "type": "string",
                "required": False,
                "description": "Tipo: api_key, access_token, refresh_token",
                "validators": [],
            },
        },
        "guards": ["No guardar tokens en texto plano"],
        "side_effects": [],
        "example": 'python vault_tokens.py --project "mi-api" --action "list"\npython vault_tokens.py --project "mi-api" --action "add" --token_type "api_key"',
        "related": ["vault_token_counter", "vault_token_service"],
    },
    "vault_token_counter": {
        "name": "vault_token_counter",
        "script": "vault_token_counter.py",
        "group": "Tokens",
        "purpose": "Cuenta tokens de contenido.",
        "params": {
            "content": {
                "type": "string",
                "required": True,
                "description": "Contenido a contar",
                "validators": [],
            },
            "model": {
                "type": "string",
                "required": False,
                "description": "Modelo: gpt-4, gpt-3.5-turbo (default: gpt-4)",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": 'python vault_token_counter.py --content "Hello world"',
        "related": ["vault_tokens", "vault_token_service"],
    },
    "vault_token_service": {
        "name": "vault_token_service",
        "script": "vault_token_service.py",
        "group": "Tokens",
        "purpose": "Servicio de gestión de tokens.",
        "params": {
            "action": {
                "type": "string",
                "required": True,
                "description": "Acción: estimate, budget, report",
                "validators": ["enum:estimate,budget,report"],
            },
            "project": {
                "type": "string",
                "required": False,
                "description": "Proyecto",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": [],
        "example": 'python vault_token_service.py --action "estimate" --project "mi-api"',
        "related": ["vault_tokens", "vault_token_counter"],
    },
    "vault_requirement_save": {
        "name": "vault_requirement_save",
        "script": "vault_requirement_save.py",
        "group": "Requerimientos",
        "purpose": "Guarda requerimiento del proyecto.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "title": {
                "type": "string",
                "required": True,
                "description": "Título del requerimiento",
                "validators": ["not_empty"],
            },
            "description": {
                "type": "string",
                "required": True,
                "description": "Descripción",
                "validators": ["min_length:20"],
            },
            "priority": {
                "type": "string",
                "required": True,
                "description": "Prioridad: critical, high, medium, low",
                "validators": ["enum:critical,high,medium,low"],
            },
            "status": {
                "type": "string",
                "required": False,
                "description": "Status: draft, reviewed, approved, implemented, verified, obsolete",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Crea nota en 01_Projects/{project}/requirements/"],
        "example": 'python vault_requirement_save.py --project "mi-api" --title "Auth" --description "User auth" --priority "high"',
        "related": ["vault_test_save", "vault_audit"],
    },
    "vault_test_save": {
        "name": "vault_test_save",
        "script": "vault_test_save.py",
        "group": "Tests",
        "purpose": "Guarda casos de prueba.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "name": {
                "type": "string",
                "required": True,
                "description": "Nombre del test",
                "validators": ["not_empty"],
            },
            "type": {
                "type": "string",
                "required": True,
                "description": "Tipo: unit, integration, e2e",
                "validators": ["enum:unit,integration,e2e"],
            },
            "description": {
                "type": "string",
                "required": True,
                "description": "Descripción del test",
                "validators": [],
            },
            "coverage": {
                "type": "string",
                "required": False,
                "description": "Cobertura esperada",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Crea nota en 01_Projects/{project}/tests/"],
        "example": 'python vault_test_save.py --project "mi-api" --name "User Auth" --type "unit" --description "Test login"',
        "related": ["vault_requirement_save", "vault_code_module"],
    },
    "vault_runbook_save": {
        "name": "vault_runbook_save",
        "script": "vault_runbook_save.py",
        "group": "Runbooks",
        "purpose": "Guarda runbook de operaciones.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "name": {
                "type": "string",
                "required": True,
                "description": "Nombre del runbook",
                "validators": ["not_empty"],
            },
            "trigger": {
                "type": "string",
                "required": True,
                "description": "Trigger: manual, alert, schedule",
                "validators": ["enum:manual,alert,schedule"],
            },
            "steps": {
                "type": "string",
                "required": True,
                "description": "Pasos en Markdown",
                "validators": ["min_lines:5"],
            },
        },
        "guards": [],
        "side_effects": ["Crea nota en 08_Runbooks/{project}/"],
        "example": 'python vault_runbook_save.py --project "mi-api" --name "Deploy" --trigger "manual" --steps "1. Build\\n2. Deploy"',
        "related": ["vault_runbook_log", "vault_incident_save"],
    },
    "vault_runbook_log": {
        "name": "vault_runbook_log",
        "script": "vault_runbook_log.py",
        "group": "Runbooks",
        "purpose": "Registra ejecución de runbook.",
        "params": {
            "runbook": {
                "type": "string",
                "required": True,
                "description": "Nombre del runbook",
                "validators": [],
            },
            "status": {
                "type": "string",
                "required": True,
                "description": "Status: success, failure, partial",
                "validators": ["enum:success,failure,partial"],
            },
            "output": {
                "type": "string",
                "required": False,
                "description": "Output de la ejecución",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Actualiza log del runbook"],
        "example": 'python vault_runbook_log.py --runbook "Deploy" --status "success"',
        "related": ["vault_runbook_save", "vault_audit"],
    },
    "vault_incident_save": {
        "name": "vault_incident_save",
        "script": "vault_incident_save.py",
        "group": "Producción/SRE",
        "purpose": "Registra incidente de producción.",
        "params": {
            "title": {
                "type": "string",
                "required": True,
                "description": "Título del incidente",
                "validators": ["not_empty"],
            },
            "severity": {
                "type": "string",
                "required": True,
                "description": "Severidad: SEV1, SEV2, SEV3, SEV4",
                "validators": ["enum:SEV1,SEV2,SEV3,SEV4"],
            },
            "description": {
                "type": "string",
                "required": True,
                "description": "Descripción",
                "validators": ["min_length:20"],
            },
            "timeline": {
                "type": "string",
                "required": False,
                "description": "Timeline del incidente",
                "validators": [],
            },
            "action_items": {
                "type": "string",
                "required": False,
                "description": "Action items en JSON",
                "validators": ["valid_json"],
            },
        },
        "guards": [],
        "side_effects": ["Crea nota en 02_Observability/incidents/"],
        "example": 'python vault_incident_save.py --title "API Down" --severity "SEV1" --description "Database connection failed"',
        "related": ["vault_slo_save", "vault_runbook_save"],
    },
    "vault_slo_save": {
        "name": "vault_slo_save",
        "script": "vault_slo_save.py",
        "group": "Producción/SRE",
        "purpose": "Guarda SLO (Service Level Objective).",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "name": {
                "type": "string",
                "required": True,
                "description": "Nombre del SLO",
                "validators": ["not_empty"],
            },
            "target": {
                "type": "string",
                "required": True,
                "description": "Target: 99.9%, 99.99%, etc",
                "validators": [],
            },
            "description": {
                "type": "string",
                "required": True,
                "description": "Descripción del SLO",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Crea nota en 02_Observability/slos/"],
        "example": 'python vault_slo_save.py --project "mi-api" --name "API Availability" --target "99.9%" --description "API uptime"',
        "related": ["vault_incident_save", "vault_audit"],
    },
    "vault_release_save": {
        "name": "vault_release_save",
        "script": "vault_release_save.py",
        "group": "Release",
        "purpose": "Guarda información de release.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "version": {
                "type": "string",
                "required": True,
                "description": "Versión (semver)",
                "validators": [],
            },
            "description": {
                "type": "string",
                "required": True,
                "description": "Descripción del release",
                "validators": [],
            },
            "changes": {
                "type": "string",
                "required": False,
                "description": "Cambios en JSON",
                "validators": ["valid_json"],
            },
        },
        "guards": [],
        "side_effects": ["Crea nota en 01_Projects/{project}/releases/"],
        "example": 'python vault_release_save.py --project "mi-api" --version "1.2.0" --description "New features"',
        "related": ["vault_change_log", "vault_incident_save"],
    },
    "vault_risk_save": {
        "name": "vault_risk_save",
        "script": "vault_risk_save.py",
        "group": "Riesgos/Calidad",
        "purpose": "Registra riesgo del proyecto.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "title": {
                "type": "string",
                "required": True,
                "description": "Título del riesgo",
                "validators": ["not_empty"],
            },
            "probability": {
                "type": "string",
                "required": True,
                "description": "Probabilidad: low, medium, high",
                "validators": ["enum:low,medium,high"],
            },
            "impact": {
                "type": "string",
                "required": True,
                "description": "Impacto: low, medium, high, critical",
                "validators": ["enum:low,medium,high,critical"],
            },
            "description": {
                "type": "string",
                "required": True,
                "description": "Descripción",
                "validators": ["min_length:20"],
            },
            "mitigation": {
                "type": "string",
                "required": False,
                "description": "Mitigación propuesta",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Crea nota en 01_Projects/{project}/risks/"],
        "example": 'python vault_risk_save.py --project "mi-api" --title "DB Failure" --probability "low" --impact "critical"',
        "related": ["vault_ncr_save", "vault_privacy_save"],
    },
    "vault_privacy_save": {
        "name": "vault_privacy_save",
        "script": "vault_privacy_save.py",
        "group": "Riesgos/Calidad",
        "purpose": "Gestiona privacidad de datos.",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "data_type": {
                "type": "string",
                "required": True,
                "description": "Tipo de dato sensible",
                "validators": [],
            },
            "classification": {
                "type": "string",
                "required": True,
                "description": "Clasificación: public, internal, confidential, restricted",
                "validators": ["enum:public,internal,confidential,restricted"],
            },
            "description": {
                "type": "string",
                "required": True,
                "description": "Descripción del dato",
                "validators": [],
            },
            "third_parties": {
                "type": "string",
                "required": False,
                "description": "Terceros en JSON",
                "validators": ["valid_json"],
            },
        },
        "guards": [],
        "side_effects": ["Crea nota en 02_Observability/privacy/"],
        "example": 'python vault_privacy_save.py --project "mi-api" --data_type "email" --classification "confidential" --description "User email"',
        "related": ["vault_risk_save", "vault_security_scan"],
    },
    "vault_ncr_save": {
        "name": "vault_ncr_save",
        "script": "vault_ncr_save.py",
        "group": "Riesgos/Calidad",
        "purpose": "Registra No Conformidad (NCR).",
        "params": {
            "project": {
                "type": "string",
                "required": True,
                "description": "Proyecto",
                "validators": [],
            },
            "title": {
                "type": "string",
                "required": True,
                "description": "Título de la NCR",
                "validators": ["not_empty"],
            },
            "description": {
                "type": "string",
                "required": True,
                "description": "Descripción",
                "validators": ["min_length:20"],
            },
            "severity": {
                "type": "string",
                "required": True,
                "description": "Severidad: minor, major, critical",
                "validators": ["enum:minor,major,critical"],
            },
            "detected_by": {
                "type": "string",
                "required": True,
                "description": "Detectado por: audit, customer, internal, automated",
                "validators": ["enum:audit,customer,internal,automated"],
            },
            "root_cause": {
                "type": "string",
                "required": False,
                "description": "Causa raíz",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Crea nota en 02_Observability/ncr/"],
        "example": 'python vault_ncr_save.py --project "mi-api" --title "Missing validation" --severity "major" --detected_by "audit"',
        "related": ["vault_risk_save", "vault_audit"],
    },
    "vault_migrate_docs": {
        "name": "vault_migrate_docs",
        "script": "vault_migrate_docs.py",
        "group": "Migración",
        "purpose": "Migra documentación entre vaults o estructuras.",
        "params": {
            "source": {
                "type": "string",
                "required": True,
                "description": "Vault o carpeta fuente",
                "validators": [],
            },
            "target": {
                "type": "string",
                "required": True,
                "description": "Carpeta destino",
                "validators": [],
            },
            "mapping": {
                "type": "string",
                "required": False,
                "description": "Mapeo de rutas en JSON",
                "validators": ["valid_json"],
            },
            "dry_run": {
                "type": "boolean",
                "required": False,
                "description": "Simular sin aplicar",
                "validators": [],
            },
        },
        "guards": ["Hacer backup antes de migrar"],
        "side_effects": ["Copia/move archivos"],
        "example": 'python vault_migrate_docs.py --source "/old-vault" --target "01_Projects" --dry_run',
        "related": ["vault_migrate_rollback", "vault_merge"],
    },
    "vault_migrate_rollback": {
        "name": "vault_migrate_rollback",
        "script": "vault_migrate_rollback.py",
        "group": "Migración",
        "purpose": "Revierte migración anterior.",
        "params": {
            "migration_id": {
                "type": "string",
                "required": True,
                "description": "ID de la migración a revertir",
                "validators": [],
            },
            "dry_run": {
                "type": "boolean",
                "required": False,
                "description": "Simular sin aplicar",
                "validators": [],
            },
        },
        "guards": ["Confirmar antes de revertir"],
        "side_effects": ["Revierte archivos migrados"],
        "example": 'python vault_migrate_rollback.py --migration_id "2026-06-24-001"\npython vault_migrate_rollback.py --migration_id "2026-06-24-001" --dry_run',
        "related": ["vault_migrate_docs", "vault_backup"],
    },
    "vault_bibliography_save": {
        "name": "vault_bibliography_save",
        "script": "vault_bibliography_save.py",
        "group": "Bibliografía",
        "purpose": "Guarda referencia bibliográfica.",
        "params": {
            "title": {
                "type": "string",
                "required": True,
                "description": "Título",
                "validators": ["not_empty"],
            },
            "type": {
                "type": "string",
                "required": True,
                "description": "Tipo: book, article, website, paper",
                "validators": ["enum:book,article,website,paper"],
            },
            "authors": {
                "type": "string",
                "required": True,
                "description": "Autores separados por coma",
                "validators": [],
            },
            "year": {
                "type": "string",
                "required": True,
                "description": "Año de publicación",
                "validators": [],
            },
            "url": {
                "type": "string",
                "required": False,
                "description": "URL",
                "validators": [],
            },
            "tags": {
                "type": "string",
                "required": False,
                "description": "Tags separados por espacio",
                "validators": [],
            },
        },
        "guards": [],
        "side_effects": ["Crea nota en 07_Knowledge/bibliography/"],
        "example": 'python vault_bibliography_save.py --title "Clean Code" --type "book" --authors "Robert Martin" --year "2008"',
        "related": ["vault_knowledge_save", "vault_search"],
    },
}


GROUPS: Dict[str, List[str]] = {
    "Core": [
        "vault_write",
        "vault_read",
        "vault_search",
        "vault_list",
        "vault_append",
        "vault_diff",
        "vault_merge",
        "vault_move",
    ],
    "Observabilidad": ["vault_log_error"],
    "Salud del Vault": ["vault_audit", "vault_validate", "vault_graph"],
    "Patrones": ["vault_pattern_save", "vault_pattern_list"],
    "Diagramas": [
        "vault_diagram_save",
        "vault_relation_add",
        "vault_mermaid_check",
        "vault_diagram_export",
    ],
    "Conocimiento": ["vault_knowledge_save", "vault_knowledge_get"],
    "Runbooks": ["vault_runbook_save", "vault_runbook_log"],
    "Infraestructura": [
        "vault_infra_save",
        "vault_infra_map",
        "vault_env_save",
        "vault_env_matrix",
    ],
    "Migración": ["vault_migrate_docs", "vault_migrate_rollback"],
    "Línea de Tiempo": ["vault_timeline"],
    "Vista del Proyecto": ["vault_project_status", "vault_project_overview"],
    "Código": [
        "vault_code_module",
        "vault_code_relation",
        "vault_code_map",
        "vault_code_query",
        "vault_code_sync",
        "vault_code_tag",
    ],
    "Backups": ["vault_backup", "vault_backup_list", "vault_restore"],
    "Seguridad": ["vault_security_scan"],
    "Índices": ["vault_section_index", "vault_master_index", "vault_reindex"],
    "Bibliografía": ["vault_bibliography_save"],
    "Drift Detection": ["vault_drift_detect"],
    "Flujos": ["vault_flow_save"],
    "Requerimientos": ["vault_requirement_save"],
    "Tests": ["vault_test_save"],
    "IA Governance": ["vault_ai_decision"],
    "Change Log": ["vault_change_log"],
    "Data Quality": ["vault_quality_check", "vault_fundamentals"],
    "Propagación": ["vault_impact", "vault_propagate"],
    "Tokens": ["vault_tokens", "vault_token_counter", "vault_token_service"],
    "Session Delta y Tags": ["vault_delta", "vault_tags"],
    "Normas": ["vault_norms", "vault_code_tag"],
    "Producción/SRE": ["vault_incident_save", "vault_slo_save"],
    "Release": ["vault_release_save"],
    "Riesgos/Calidad": ["vault_risk_save", "vault_privacy_save", "vault_ncr_save"],
    "Bootstrap": ["vault_init"],
    "Corrección Automática": ["vault_fix_brackets"],
    "Versionado": ["vault_standard_upgrade"],
    "Gestión de Carpetas": ["vault_folder_registry"],
}


VALIDATORS: Dict[str, callable] = {}


def get_tool(name: str) -> Optional[Dict[str, Any]]:
    """Retorna la definición de una tool por nombre."""
    return TOOLS_CATALOG.get(name)


def get_group_tools(group: str) -> List[Dict[str, Any]]:
    """Retorna todas las tools de un grupo."""
    tool_names = GROUPS.get(group, [])
    return [TOOLS_CATALOG.get(name) for name in tool_names if name in TOOLS_CATALOG]


def get_all_groups() -> List[str]:
    """Retorna lista de todos los grupos."""
    return list(GROUPS.keys())


def find_tools_by_purpose(query: str) -> List[Dict[str, Any]]:
    """Busca tools por propósito o palabra clave."""
    query = query.lower()
    results = []
    for name, tool in TOOLS_CATALOG.items():
        if query in tool["purpose"].lower() or query in name.lower():
            results.append(tool)
    return results


def get_related_tools(name: str) -> List[Dict[str, Any]]:
    """Retorna tools relacionadas."""
    tool = TOOLS_CATALOG.get(name)
    if not tool:
        return []
    related_names = tool.get("related", [])
    return [TOOLS_CATALOG.get(n) for n in related_names if n in TOOLS_CATALOG]
